language: node_js
node_js:
- '18'
before_install:
- openssl aes-256-cbc -K $encrypted_189e52c2c347_key -iv $encrypted_189e52c2c347_iv
  -in deploy_key.enc -out deploy_key -d
- openssl aes-256-cbc -K $encrypted_key -iv $encrypted_iv -in deploy_key.enc -out
  deploy_key -d
- chmod 600 deploy_key
- eval "$(ssh-agent -s)"
- ssh-add deploy_key
install:
- npm install
script:
- npm run build
deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: main
